### ISSUE TITLE
There is no v10 of NPM.

### ISSUE THREAD

**Issue by jonathan-meyer** [crucialfelix/generator-minimal-typescript#8]
https://github.com/crucialfelix/generator-minimal-typescript/blob/976ff1b3d8f3f1e90eeaff7288b178d086d0abe0/package.json#L21

<img width="831" alt="image" src="https://user-images.githubusercontent.com/20321382/201687304-15b3edb3-7e71-43ef-b5aa-8bf7a1da5353.png">

**Comment by crucialfelix** [comment]
Typo indeed. Thanks
